### ISSUE TITLE
프로젝트 지출 내역 정리

### ISSUE THREAD

**Issue by Oryuca** [JeMinMoon/Career-Path-Recommendation#5]
Mongo DB Atlas
완전 관리형 클라우드 데이터베이스 서비스
데이터베이스를 클라우드에서 호스팅 하고 관리하는 것을 중심으로 하며, 개발자 및 기업이 손쉽게 애플리케이션을 빌드하고 배포할 수 있도록 지원
요금 지불 방식: https://www.mongodb.com/ko-kr/pricing

Neo4j
그래프 데이터베이스 관리 시스템
그래프 데이터 저장 및 처리 능력을 가진 ACID 호환 트랜잭션 데이터베이스로 설명
요금 지불 방식: https://neo4j.com/pricing/

AWS( Amazon Web Services) S3
확장성, 데이터 가용성 및 보안과 성능을 제공하는 객체 스토리지 서비스
데이터 레이크, 웹사이트, 클라우드 네이티브 애플리케이션, 백업, 아카이브, 기계 학습 및 분석과 같은 다양한 사용 사례에 대해 원하는 양의 데이터를 저장하고 보호
요금 지불 방식:  https://aws.amazon.com/ko/pricing/?nc2=h_ql_pr_ln&aws-products-pricing.sort-by=item.additionalFields.productNameLowercase&aws-products-pricing.sort-order=asc&awsf.Free%20Tier%20Type=*all&awsf.tech-category=*all

AWS(Amazon Web Services) EC2
클라우드 컴퓨팅 서비스 -> 클라우드 서비스는 내가 컴퓨터, 인프라를 소유하지 않고도 IT인프라를 필요한 만큼 비용을 내고 사용하여 
물리적인 인프라 없이 소프트웨어 만으로도 IT인프라를 사용할 수 있음
요금 지불 방식: https://aws.amazon.com/ko/ec2/pricing/

이 이외에도 프로젝트에 필요한 지출 내역이 있다면 계속 추가해 주세요

**Comment by JeMinMoon** [comment]
OpenAI api
요금 지불 방식: https://openai.com/pricing
GPT-3.5 Turbo를 사용할 것으로 예상됨.

**Comment by merjunemong** [comment]
서비스를 위해 웹사이트 프론트를 개발할 때, 웹 디자인 템플릿을 유료로 구매해서도 사용할 수 있을 것 같습니다.
(Pro 구독 같은것이 아닌 템플릿 하나씩 구매하는 형식)

- BootStrap(https://themes.getbootstrap.com/ )
- Argon Jekyll Themes(https://jekyllthemes.io/theme/argon-jekyll-theme )
